### ISSUE TITLE
Simplest way to install sbt ?

### ISSUE THREAD

**Issue by tfindlay-au** [saubury/tw-scala-bootcamp#1]
Currently:
https://github.com/saubury/tw-scala-bootcamp/blob/b1f72cfac2a6bd65118f5d8e8f98f4b09b4d205f/docker/Dockerfile#L17

This approach adds a few steps to add an repoistory, however as we are using wget to pull down a tarball for scala, would it be simpler to do the same for sbt ?

Proposed:
curl -L https://piccolo.link/sbt-1.3.0.tgz | tar xvz -C .
or use a package...
wget https://dl.bintray.com/sbt/debian/sbt-1.3.4.deb && dpkg -i sbt-1.3.4.deb && rm sbt-1.3.4.deb

**Comment by saubury** [comment]
not fussed; as long as it works and the REPL operates correctly
